const predefinedChecklists = [
    {
        checklistType: 'Morning',
        items: [
            { name: '7 Hours Sleep', completed: false },
            { name: 'Drink a full glass of warm water with lemon and honey', completed: false },
            { name: 'Stretch', completed: false },
            { name: 'Tahajjud', completed: false },
            { name: 'Quick yoga', completed: false },
            { name: 'Fajr', completed: false },
            { name: 'Quran', completed: false },
            { name: 'Sunrise', completed: false },
            { name: 'Jog', completed: false },
            { name: 'Time in nature', completed: false },
            { name: 'Meditation', completed: false },
            { name: 'Breathwork', completed: false },
            { name: 'Gratitude', completed: false },
            { name: 'Ishraq', completed: false },
            { name: 'Intermittent Fasting', completed: false },
            { name: 'Coffee + Apple (Makes you alert)', completed: false },
            { name: 'Morning Family Time', completed: false },
            { name: 'Cold Shower', completed: false },
            { name: 'Heavy Breakfast', completed: false },
            { name: 'Multivitamins - Zinc + Other minerals to help keep the bodily functions running', completed: false },
            { name: 'Omega 3', completed: false },
            { name: 'Morning Drive', completed: false },
            { name: 'Peppermint Essential Oil for Allergies and Being Active', completed: false },
        ],
    },
    {
        checklistType: 'LateMorning',
        items: [
            { name: 'Green Tea', completed: false },
            { name: 'Journaling', completed: false },
            { name: 'Day Planning', completed: false },
            { name: 'Learning and Implementation', completed: false },
            { name: 'Review the goals', completed: false },
            { name: 'Brunch: Fruits', completed: false },
            { name: 'Chasht', completed: false },
            { name: '2 Priorities Nailed (80% Work done)', completed: false },
        ],
    },
    {
        checklistType: 'Afternoon',
        items: [
            { name: 'Energetic Lunch - Beef steak + Meshed Potatoes', completed: false },
            { name: 'Walk After Lunch', completed: false },
            { name: 'Zohr', completed: false },
            { name: 'Call spouse', completed: false },
            { name: 'Third Priority Nailed (99% Work done)', completed: false },
            { name: 'CAC - before workout - restore calcium for smooth muscle movement and strong bones 2000mg daily', completed: false },
            { name: 'Pre-workout energy - Bananas and nuts', completed: false },
            { name: 'Call Family', completed: false },
        ],
    },
    {
        checklistType: 'Evening',
        items: [
            { name: 'Exercise', completed: false },
            { name: 'During workout - Grapefruit Orange juice', completed: false },
            { name: 'Post-workout - Protein shake and egg whites', completed: false },
            { name: 'Asr', completed: false },
            { name: 'Sunset', completed: false },
            { name: 'Supper: Yogurt + Nuts + Seeds + Bananas (Induces sleep)', completed: false },
            { name: 'Magrib', completed: false },
            { name: 'Awabin', completed: false },
            { name: 'Quran', completed: false },
            { name: 'Light Dinner - Salmon or Turkey baked', completed: false },
            { name: 'Isha', completed: false },
            { name: 'Quran', completed: false },
            { name: 'Walk after Dinner', completed: false },
        ],
    },
    {
        checklistType: 'Night',
        items: [
            { name: 'Check weather and traffic news', completed: false },
            { name: 'Prepare outfit', completed: false },
            { name: 'Pack bag', completed: false },
            { name: 'Wind-down and Relax', completed: false },
            { name: 'Chamomile or Lavender Tea', completed: false },
            { name: 'Lukewarm shower night', completed: false },
            { name: 'Night family time', completed: false },
            { name: 'Before Bed: Oats + nuts + fruits + Warm milk and honey (Induces Sleep)', completed: false },
            { name: 'Magnesium - Better sleep and muscle improvements', completed: false },
            { name: 'Read book', completed: false },
            { name: 'Take steam', completed: false },
            { name: 'Humidifier + Calming background sound', completed: false },
            { name: 'Limit water intake', completed: false },
        ],
    },
];

module.exports = predefinedChecklists;
